config/routes.rb
Rails.application.routes.draw do
  root 'dots#index'
  resources :dots, only: %i[index update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dot.rb
class Dot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dots_controller.rb
class DotsController < ApplicationController
  def index
    @dots_by_rows = uniqe_rows.map do |row|
      Dot.where(row:).limit(dot_limit)
    end
  end

  def update
    @dot = Dot.find(params[:id])
    @previous_dot = Dot.find_by(row: @dot.row, enabled: true)
    @dot.toggle!(:enabled)
    
    @previous_dot.toggle!(:enabled) if @previous_dot && @previous_dot != @dot
  end

  private

  def uniqe_rows
    Dot.pluck(:row).uniq
  end

  def dot_limit
    params[:dot_limit] || 3
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dots/_dot.html.erb
<%= render DotComponent.new(dot: dot) %>

app/views/dots/_dots_select.html.erb
<%= form_with url: dots_path, method: :get, data: { turbo_frame: 'dots' }  do |f| %>
  <%= f.select :dot_limit, 1..3, {}, {onchange: 'this.form.requestSubmit()'} %>
<% end %>

app/views/dots/index.html.erb
<%= render 'dots_select' %>
<%= render 'dots_select' %>

<%= turbo_frame_tag 'dots' do %>
  <div style="display: flex">
    <% @dots_by_rows.each do |row| %>
      <%= render row %>
      <br>
    <% end %>
  </div>
<% end %>

app/views/dots/update.turbo_stream.erb
<%= turbo_stream.update @dot %>
<%= turbo_stream.update @previous_dot if @previous_dot && @previous_dot != @dot%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kropki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div id="root">
  <div class="app">
    <%= yield %>
  </div>
  </div>
    <%= console if Rails.env.development? %>
  </body>
</html>